import OpenAI from "openai";
import { config } from "./config.js";

/**
 * Current men's style/grooming trends, generated by the LLM and cached so we
 * only pay for a refresh roughly once per day per (faceShape, month) key.
 */

let openai: OpenAI | null = null;
function getOpenAI(): OpenAI | null {
  if (!config.openaiApiKey) return null;
  if (!openai) openai = new OpenAI({ apiKey: config.openaiApiKey });
  return openai;
}

export type TrendCategory = "hair" | "fashion" | "grooming" | "accessories";

export interface TrendItem {
  title: string;
  category: TrendCategory;
  description: string;
  why: string;
}

export interface TrendsResult {
  generatedAt: string;
  season: string;
  faceShape?: string;
  items: TrendItem[];
}

const CACHE = new Map<string, { expires: number; data: TrendsResult }>();
const TTL_MS = 24 * 60 * 60 * 1000;

function currentSeason(date = new Date()): string {
  const m = date.getMonth(); // 0-11 (northern hemisphere)
  const year = date.getFullYear();
  if (m <= 1 || m === 11) return `Winter ${year}`;
  if (m <= 4) return `Spring ${year}`;
  if (m <= 7) return `Summer ${year}`;
  return `Fall ${year}`;
}

export async function getTrends(faceShape?: string): Promise<TrendsResult> {
  const season = currentSeason();
  const key = `${season}|${faceShape ?? "any"}`;
  const cached = CACHE.get(key);
  if (cached && cached.expires > Date.now()) return cached.data;

  const data = await generate(season, faceShape);
  CACHE.set(key, { expires: Date.now() + TTL_MS, data });
  return data;
}

async function generate(season: string, faceShape?: string): Promise<TrendsResult> {
  const client = getOpenAI();
  if (!client) return fallback(season, faceShape);

  const shapeLine = faceShape
    ? `The user has a ${faceShape} face shape — for hair/grooming items, tailor the recommendation to flatter that shape.`
    : `Keep hair/grooming items broadly flattering.`;

  const sys = [
    "You are a men's style and grooming editor for a self-improvement app.",
    `Produce a concise list of CURRENT, realistic men's trends for ${season}.`,
    shapeLine,
    "Cover a mix across categories: hair, fashion, grooming, accessories.",
    "Be specific and practical (no fabricated brand names, no celebrity names, no medical claims).",
    "Return STRICT JSON: {\"items\":[{\"title\":string,\"category\":\"hair\"|\"fashion\"|\"grooming\"|\"accessories\",\"description\":string,\"why\":string}]} with 8-10 items.",
    "description = one short sentence on the trend. why = one short sentence on why it works / who it suits.",
  ].join("\n");

  try {
    const completion = await client.chat.completions.create({
      model: config.rizzModel,
      temperature: 0.8,
      max_tokens: 900,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: sys },
        { role: "user", content: `Give me this ${season} men's trend list${faceShape ? ` for a ${faceShape} face` : ""}.` },
      ],
    });
    const raw = completion.choices[0]?.message?.content ?? "{}";
    const parsed = JSON.parse(raw) as { items?: unknown };
    const items = normalizeItems(parsed.items);
    if (items.length === 0) return fallback(season, faceShape);
    return { generatedAt: new Date().toISOString(), season, faceShape, items };
  } catch {
    return fallback(season, faceShape);
  }
}

function normalizeItems(input: unknown): TrendItem[] {
  if (!Array.isArray(input)) return [];
  const allowed: TrendCategory[] = ["hair", "fashion", "grooming", "accessories"];
  const out: TrendItem[] = [];
  for (const r of input) {
    if (!r || typeof r !== "object") continue;
    const o = r as Record<string, unknown>;
    const title = typeof o.title === "string" ? o.title.slice(0, 80) : "";
    const cat = typeof o.category === "string" ? (o.category as TrendCategory) : "fashion";
    const description = typeof o.description === "string" ? o.description.slice(0, 280) : "";
    const why = typeof o.why === "string" ? o.why.slice(0, 280) : "";
    if (!title || !description) continue;
    out.push({
      title,
      category: allowed.includes(cat) ? cat : "fashion",
      description,
      why,
    });
    if (out.length >= 12) break;
  }
  return out;
}

function fallback(season: string, faceShape?: string): TrendsResult {
  return {
    generatedAt: new Date().toISOString(),
    season,
    faceShape,
    items: [
      { title: "Textured, lower-maintenance crops", category: "hair", description: "Short, piece-y cuts with natural movement are dominating.", why: "Easy to style and flatter most face shapes." },
      { title: "Neat, well-groomed stubble", category: "grooming", description: "Defined short stubble with a clean neckline.", why: "Adds structure to the jaw without high upkeep." },
      { title: "Earth-tone layering", category: "fashion", description: "Olive, tan, and brown tonal outfits.", why: "Versatile, warm, and easy to mix." },
      { title: "Relaxed straight-leg trousers", category: "fashion", description: "Tailored but easy through the leg.", why: "Balanced silhouette that suits most builds." },
      { title: "Minimal everyday fragrance", category: "grooming", description: "Clean, fresh scents over heavy ones.", why: "Approachable and office-friendly." },
      { title: "Slim leather strap watch", category: "accessories", description: "Understated dial with a thin strap.", why: "Elevates a simple outfit instantly." },
    ],
  };
}
